workflows:
  build:
    name: Build iOS App
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
      - name: Clean and Install Pods
        script: |
          rm -rf Pods
          rm Podfile.lock
          pod install
      - name: Build iOS App
        script: |
          xcodebuild -workspace technocorner.xcworkspace -scheme technocorner -sdk iphoneos -configuration Release archive -archivePath $HOME/technocorner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/technocorner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $HOME/technocorner.ipa
    artifacts:
      - $HOME/technocorner.ipa
